import test from 'node:test';
import assert from 'node:assert/strict';
import {createAssetServices,payloadFor,fieldsFor,safeStaff,confirmedDeactivation} from '../src/api/assets.js';
import {createApiClient} from '../src/api/client.js';
import {createSession} from '../src/api/session.js';
const inputs={buildings:{customerProfileId:'12',buildingName:'Tower'},lifts:{buildingId:'13',name:'Passenger lift'},amc:{liftId:'14',amcNumber:'test-contract',plan:'Basic',startDate:'2026-09-11',endDate:'2027-09-10'}};
function fixture(response){const calls=[];const api=createAssetServices({request:async(path,options)=>{calls.push({path,options});if(response instanceof Error)throw response;return response;}});return {api,calls};}
for(const [kind,path] of Object.entries({buildings:'/buildings',lifts:'/lifts',amc:'/amc-contracts'})){
 test(kind+' list and create use canonical endpoint and whitelist payload',async()=>{const f=fixture([{id:1}]);assert.deepEqual(await f.api[kind].list(),[{id:1}]);assert.equal(f.calls[0].path,path);const g=fixture({id:7});assert.equal((await g.api[kind].create({...inputs[kind],customerId:999,statusCalculated:'fake'})).id,7);assert.equal(g.calls[0].path,path);assert.equal(g.calls[0].options.method,'POST');assert(!Object.hasOwn(g.calls[0].options.body,'customerId'));assert(!Object.hasOwn(g.calls[0].options.body,'statusCalculated'));});
 test(kind+' rejects malformed/null lists and preserves empty and optional-null values',async()=>{assert.deepEqual(await fixture([]).api[kind].list(),[]);assert.deepEqual(await fixture([{id:1,city:null,nextMaintenanceDate:null}]).api[kind].list(),[{id:1,city:null,nextMaintenanceDate:null}]);for(const value of [null,{},[{id:0}]])await assert.rejects(fixture(value).api[kind].list(),{status:502});});
 if(kind!=='amc')test(kind+' update preserves owner and DELETE waits for server',async()=>{const f=fixture({id:7});const original={...inputs[kind],id:7};await f.api[kind].update(original,inputs[kind]);assert.equal(f.calls[0].path,path+'/7');assert.equal(f.calls[0].options.method,'PUT');const owner=kind==='buildings'?'customerProfileId':'buildingId';await assert.rejects(f.api[kind].update(original,{...inputs[kind],[owner]:99}),{status:400});const d=fixture(null);assert.equal(await d.api[kind].deactivate(7),null);assert.equal(d.calls[0].path,path+'/7');assert.equal(d.calls[0].options.method,'DELETE');});
}
test('deactivation requires confirmation and propagates backend failure without optimistic success',async()=>{let count=0;const api={deactivate:async()=>{count++;throw new Error('failed');}};assert.equal(await confirmedDeactivation(api,1,()=>false),false);assert.equal(count,0);await assert.rejects(confirmedDeactivation(api,1,()=>true));assert.equal(count,1);});
test('AMC renew sends exact renewal fields; never sends authoritative status or coverage',async()=>{const f=fixture({id:2,status:'RENEWED',covered:false});const result=await f.api.amc.renew({id:2,endDate:'2026-09-10'},{...inputs.amc,status:'ACTIVE',covered:true});assert.equal(result.status,'RENEWED');assert.equal(result.covered,false);assert.equal(f.calls[0].path,'/amc-contracts/2/renew');assert.equal(f.calls[0].options.method,'PUT');for(const key of ['id','liftId','amcNumber','status','covered'])assert(!Object.hasOwn(f.calls[0].options.body,key));assert.equal(f.api.amc.deactivate,undefined);});
test('date, integer, status and length constraints reject invalid asset input',()=>{for(const draft of [{...inputs.lifts,healthScore:101},{...inputs.lifts,healthScore:-1},{...inputs.lifts,healthScore:1.5},{...inputs.lifts,currentStatus:'IN_PROGRESS'},{...inputs.lifts,buildingId:0},{...inputs.lifts,installationDate:'2026-02-30'},{...inputs.lifts,name:'x'.repeat(161)}])assert.throws(()=>payloadFor('lifts',draft),{status:400});assert.equal(payloadFor('lifts',{...inputs.lifts,healthScore:'0',nextMaintenanceDate:''}).healthScore,0);assert.equal(payloadFor('lifts',inputs.lifts).nextMaintenanceDate,null);assert.throws(()=>payloadFor('amc',{...inputs.amc,endDate:'2020-01-01'}),{status:400});assert.throws(()=>payloadFor('amc',inputs.amc,'renew',{endDate:'2026-09-11'}),{status:400});assert.throws(()=>payloadFor('buildings',{...inputs.buildings,buildingName:' '}),{status:400});});
test('staff roles and technician fields follow backend rules',()=>{for(const role of ['CUSTOMER','SUPER_ADMIN',''])assert.throws(()=>payloadFor('staff',{email:'test@example.invalid',password:'test-only',role}),{status:400});const admin=payloadFor('staff',{email:' TEST@EXAMPLE.INVALID ',password:'test-only',role:'ADMIN',employeeId:'ignored'});assert.equal(admin.email,'test@example.invalid');assert(!Object.hasOwn(admin,'employeeId'));const tech=payloadFor('staff',{email:'test@example.invalid',password:'test-only',role:'TECHNICIAN'});assert.equal(tech.availabilityStatus,'AVAILABLE');assert.equal(tech.employeeId,null);for(const availabilityStatus of ['AVAILABLE','BUSY','OFF_DUTY','ON_LEAVE'])assert.equal(payloadFor('staff',{...tech,availabilityStatus}).availabilityStatus,availabilityStatus);assert.throws(()=>payloadFor('staff',{...tech,availabilityStatus:'ACTIVE'}),{status:400});assert.throws(()=>payloadFor('staff',{...tech,employeeId:'x'.repeat(51)}),{status:400});assert.throws(()=>payloadFor('staff',{...tech,password:'x'.repeat(73)}),{status:400});assert(!fieldsFor('staff','create','ADMIN').some(f=>f.key==='specialization'));});
test('staff creation/deactivation use supported routes and exclude response passwords',async()=>{const f=fixture({userId:5,role:'TECHNICIAN',active:true,password:'must-not-return',passwordHash:'must-not-return'});const result=await f.api.staff.create({email:'test@example.invalid',password:'test-only',role:'TECHNICIAN'});assert.equal(f.calls[0].path,'/admin/users');assert.equal(f.calls[0].options.method,'POST');assert(!JSON.stringify(result).includes('must-not-return'));await f.api.staff.deactivate(5);assert.equal(f.calls[1].path,'/admin/users/5');assert.equal(f.calls[1].options.method,'DELETE');assert.equal(f.api.staff.list,undefined);assert.equal(f.api.staff.get,undefined);assert.equal(f.api.staff.search,undefined);assert.throws(()=>safeStaff({userId:5,role:'CUSTOMER'}),{status:502});});
test('asset requests reuse v1 envelope handling, refresh once on 401, retain session on 403',async()=>{const session=createSession();session.set({accessToken:'test-old',refreshToken:'test-refresh'});let refresh=0;const client=createApiClient({session,fetchImpl:async(url,o)=>{let data=[{id:1}],status=200;if(url.endsWith('/auth/refresh')){refresh++;data={accessToken:'test-new',refreshToken:'test-rotated'};}else if(o.headers.Authorization==='Bearer test-old')status=401;assert(url.includes('/api/v1/'));return {ok:status===200,status,json:async()=>({success:status===200,status,data})};}});assert.deepEqual(await createAssetServices(client).buildings.list(),[{id:1}]);assert.equal(refresh,1);for(const status of [400,403,409,500]){const denied=createAssetServices(createApiClient({session,fetchImpl:async()=>({ok:false,status,json:async()=>({success:false,status,data:null})})}));await assert.rejects(denied.lifts.create(inputs.lifts),{status});assert(session.get());}});
test('active Stage 2 source has no obsolete routes, mock records or duplicate token handling',async()=>{const {readFile}=await import('node:fs/promises');const entry=await readFile(new URL('../src/main.jsx',import.meta.url),'utf8');const service=await readFile(new URL('../src/api/assets.js',import.meta.url),'utf8');const view=await readFile(new URL('../src/assetModules.jsx',import.meta.url),'utf8');assert(!entry.includes("from './adminModules'"));for(const text of [entry,service,view]){assert(!/\/api\/admin|\/api\/amcs|\/api\/buildings|\/api\/lifts|Apex Towers|Mehta Residency|console\.(log|debug|info)/.test(text));}assert(!/fetch\(|localStorage|sessionStorage|refreshToken|accessToken/.test(service+view));});
