import React,{useEffect,useState} from 'react';
import {isAdmin} from './api/services.js';
import {ErrorState,displayValue} from './assetModules.jsx';
import {Pager,DetailPage} from './workflowModules.jsx';
import {customerStatuses} from './api/customers.js';
import {priorities,statuses} from './api/workflow.js';
import { DataTable, PriorityChip, StatusChip } from './uiPatterns.jsx';

function CustomerForm({mode,original,onSubmit,onClose,busy,error}) {
 const [draft,setDraft]=useState(()=>original||{});
 const fields=[...(mode==='create'?[['email','Email','email'],['phone','Phone','tel'],['password','Temporary password','password']]:[]),['fullName','Full name','text'],['alternatePhone','Alternate phone','tel'],['companyName','Company name','text'],['address','Address','text']];
 return <form className="asset-form panel" onSubmit={e=>{e.preventDefault();onSubmit(draft);}}><h2>{mode==='create'?'Create customer':'Edit customer'}</h2><p>{mode==='create'?'Creates a canonical CUSTOMER account and profile. Buildings and lifts remain separate onboarding steps.':'Only profile fields can be edited here. Identity and password changes are not supported by this contract.'}</p>
 <div className="asset-fields">{fields.map(([key,label,type])=><label key={key}>{label}{['password','fullName'].includes(key)?' *':''}<input type={type} required={['password','fullName'].includes(key)} autoComplete={type==='password'?'new-password':'off'} maxLength={key==='address'?500:key==='companyName'?200:key==='fullName'?160:key==='email'?254:key==='password'?72:20} placeholder={key==='phone'||key==='alternatePhone'?'+919876543210':''} value={draft[key]??''} onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))}/>{mode==='create'&&key==='phone'?<small className="field-help">Use country code. A 10-digit Indian number is accepted and saved with +91.</small>:null}</label>)}</div>
 <ErrorState error={error}/><div className="page-actions"><button type="button" className="secondary-btn" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Saving...':'Save customer'}</button></div></form>;
}
function CustomerDetail({detail,onBack,onEdit,onDeactivate,onReactivate,busy}) {
 return <section className="asset-form panel"><div className="page-actions"><button className="secondary-btn" disabled={busy} onClick={onBack}>Back to customers</button><button className="secondary-btn" disabled={busy} onClick={()=>onEdit(detail)}>Edit</button>{detail.active?<button className="secondary-btn" disabled={busy} onClick={()=>onDeactivate(detail)}>Deactivate</button>:<button className="primary-btn" disabled={busy} onClick={()=>onReactivate(detail)}>Reactivate</button>}</div>
 <h2>{detail.fullName}</h2><dl>{['customerProfileId','userId','email','phone','alternatePhone','companyName','address','status','active','createdAt','updatedAt'].map(key=><React.Fragment key={key}><dt>{key}</dt><dd>{key==='status'?<StatusChip value={detail[key]}/>:displayValue(detail[key])}</dd></React.Fragment>)}</dl>
 <h3>Operational summary</h3><div className="kpi-grid"><section className="kpi-card"><div className="kpi-label">Buildings</div><div className="kpi-value">{detail.buildingCount}</div></section><section className="kpi-card"><div className="kpi-label">Lifts</div><div className="kpi-value">{detail.liftCount}</div></section><section className="kpi-card"><div className="kpi-label">Service requests</div><div className="kpi-value">{detail.serviceRequestCount}</div></section></div>
 <h3>Buildings</h3><DataTable empty="No buildings linked." rows={detail.buildings} columns={[{key:'id',label:'ID'},{key:'buildingName',label:'Name'},{key:'city',label:'City',render:r=>displayValue(r.city)},{key:'status',label:'Status',render:r=><StatusChip value={r.status}/>},{key:'isActive',label:'Active',render:r=>displayValue(r.isActive)}]}/>
 <h3>Lifts</h3><DataTable empty="No lifts linked." rows={detail.lifts} columns={[{key:'id',label:'ID'},{key:'buildingId',label:'Building'},{key:'name',label:'Name'},{key:'currentStatus',label:'Status',render:r=><StatusChip value={r.currentStatus}/>},{key:'isActive',label:'Active',render:r=>displayValue(r.isActive)}]}/>
 <h3>Recent service requests</h3><DataTable empty="No service requests linked." rows={detail.serviceRequests} columns={[{key:'serviceId',label:'Request'},{key:'title',label:'Title'},{key:'status',label:'Status',render:r=><StatusChip value={r.status}/>},{key:'priority',label:'Priority',render:r=><PriorityChip value={r.priority}/>}]} /></section>;
}
export function CustomersPage({api,user}) {
 const [page,setPage]=useState(0),[q,setQ]=useState(''),[state,setState]=useState('all'),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[revision,setRevision]=useState(0),[view,setView]=useState(null),[detail,setDetail]=useState(null),[editor,setEditor]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const allowed=isAdmin(user);
 useEffect(()=>{if(!allowed||view||editor)return;let current=true;setData(null);setLoading(true);setError(null);const active=state==='all'?undefined:state==='active';api.list({page,size:10,q,active}).then(d=>{if(current)setData(d);}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[api,allowed,page,q,state,revision,view,editor]);
 useEffect(()=>{if(!view)return;let current=true;setDetail(null);setLoading(true);setError(null);api.detail(view).then(d=>{if(current)setDetail(d);}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[api,view,revision]);
 const save=async draft=>{setBusy(true);setError(null);setNotice('');try{const result=editor.mode==='create'?await api.create(draft):await api.update(editor.original,draft);setEditor(null);setView(result.customerProfileId);setNotice('Customer saved.');setRevision(v=>v+1);}catch(e){setError(e);}finally{setBusy(false);}};
 const lifecycle=async(customer,active)=>{if(!window.confirm((active?'Reactivate ':'Deactivate ')+customer.fullName+'?'))return;setBusy(true);setError(null);try{const result=active?await api.reactivate(customer.customerProfileId):await api.deactivate(customer.customerProfileId);setDetail(result);setNotice(active?'Customer reactivated.':'Customer deactivated. Historical records were retained.');}catch(e){setError(e);}finally{setBusy(false);}};
 if(!allowed)return <p role="alert">Access denied. Administrator role required.</p>;
 if(editor)return <CustomerForm mode={editor.mode} original={editor.original} busy={busy} error={error} onClose={()=>{setEditor(null);setError(null);}} onSubmit={save}/>;
 if(view)return <><div className="page-header"><div><div className="eyebrow">CUSTOMER MANAGEMENT</div><h1>Customer detail</h1></div></div><ErrorState error={error}/>{loading?<section className="panel empty-state" role="status">Loading customer...</section>:detail&&<CustomerDetail detail={detail} busy={busy} onBack={()=>{setView(null);setDetail(null);setRevision(v=>v+1);}} onEdit={original=>setEditor({mode:'edit',original})} onDeactivate={c=>lifecycle(c,false)} onReactivate={c=>lifecycle(c,true)}/>}</>;
 return <><div className="page-header"><div><div className="eyebrow">CUSTOMER MANAGEMENT</div><h1>Customers</h1><p>Create, update, deactivate and reactivate canonical customer accounts.</p></div><div className="page-actions"><button className="secondary-btn" disabled={loading} onClick={()=>setRevision(v=>v+1)}>Refresh</button><button className="primary-btn" onClick={()=>setEditor({mode:'create'})}>Create customer</button></div></div>{notice&&<p role="status">{notice}</p>}
 <section className="asset-form panel"><div className="table-controls"><label>Search<input maxLength={254} value={q} onChange={e=>{setQ(e.target.value);setPage(0);}} placeholder="Name, email or phone"/></label><label>State<select value={state} onChange={e=>{setState(e.target.value);setPage(0);}}>{customerStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select></label></div><ErrorState error={error}/>{loading?<p role="status">Loading customers...</p>:<DataTable empty="No customers found." rows={data?.items||[]} columns={[{key:'fullName',label:'Name'},{key:'email',label:'Email',render:c=>displayValue(c.email)},{key:'phone',label:'Phone',render:c=>displayValue(c.phone)},{key:'status',label:'Status',render:c=><StatusChip value={c.status}/>},{key:'active',label:'Active',render:c=>displayValue(c.active)}]} onRow={c=>setView(c.customerProfileId)} />}<Pager data={data} page={page} onPage={p=>{setData(null);setPage(p);}} busy={loading}/></section></>;
}
export function EmergencyQueuePage({api,user}) {
 const [page,setPage]=useState(0),[status,setStatus]=useState(''),[priority,setPriority]=useState('EMERGENCY'),[data,setData]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[view,setView]=useState(null);
 const allowed=isAdmin(user);
 const [q,setQ]=useState('');
 useEffect(()=>{if(!allowed||view)return;let current=true;setData(null);setError(null);setLoading(true);api.list({page,size:10,status,priority,q}).then(d=>{if(current)setData(d);}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[api,allowed,page,status,priority,q,revision,view]);
 if(!allowed)return <p role="alert">Access denied. Administrator role required.</p>;
 if(view)return <DetailPage id={view} api={api} onBack={()=>setView(null)}/>;
 return <><div className="page-header"><div><div className="eyebrow">URGENT OPERATIONS</div><h1>Emergency Queue</h1><p>Filtered canonical service requests. No separate emergency workflow is created.</p></div><button className="secondary-btn" disabled={loading} onClick={()=>setRevision(v=>v+1)}>Refresh queue</button></div><section className="asset-form panel"><div className="table-controls four-controls"><label>Search<input value={q} onChange={e=>{setQ(e.target.value);setPage(0);}} placeholder="Search urgent requests"/></label><label>Priority<select value={priority} onChange={e=>{setPriority(e.target.value);setPage(0);}}><option value="">All</option>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div><ErrorState error={error}/>{loading?<p role="status">Loading urgent requests...</p>:<DataTable empty="No urgent service requests found." rows={data?.items||[]} columns={[{key:'serviceId',label:'Request'},{key:'title',label:'Title'},{key:'status',label:'Status',render:r=><StatusChip value={r.status}/>},{key:'priority',label:'Priority',render:r=><PriorityChip value={r.priority}/>},{key:'serviceRequestedAt',label:'Requested',render:r=>displayValue(r.serviceRequestedAt)}]} onRow={r=>setView(r.id)} />}<Pager data={data} page={page} onPage={p=>{setData(null);setPage(p);}} busy={loading}/></section></>;
}
