import React,{useEffect,useState} from 'react';
import {notificationStatuses} from './api/notifications.js';
import {isAdmin} from './api/services.js';
import {DirectoryPicker,Pager} from './workflowModules.jsx';
import {ErrorState,displayValue} from './assetModules.jsx';
import { DataTable, StatusChip } from './uiPatterns.jsx';
export function NotificationTable({items,onOpen}){return <DataTable rows={items} empty="No notifications in this inbox page." columns={[{key:'title',label:'Title'},{key:'message',label:'Message',render:r=><span className="truncate-cell">{r.message}</span>},{key:'channel',label:'Channel',render:r=><StatusChip value={r.channel}/>},{key:'status',label:'Status',render:r=><StatusChip value={r.status}/>},{key:'scheduledAt',label:'Scheduled',render:r=>displayValue(r.scheduledAt)},{key:'sentAt',label:'Sent',render:r=>displayValue(r.sentAt)}]} onRow={onOpen}/>;}
export function ComposeNotification({api,directories,onClose,onCreated}){
 const [kind,setKind]=useState('customers'),[recipient,setRecipient]=useState(null),[draft,setDraft]=useState({title:'',message:'',scheduledAt:''}),[busy,setBusy]=useState(false),[error,setError]=useState(null);
 const submit=async e=>{e.preventDefault();setBusy(true);setError(null);try{onCreated(await api.create(draft,recipient));}catch(e){setError(e);}finally{setBusy(false);}};
 return <form className="asset-form panel" onSubmit={submit}><h2>Compose in-app notification</h2><p>Create a notification record for a selected customer or technician. It appears in their inbox when due; this is not external delivery or a sent-history view.</p><fieldset disabled={busy}><label>Recipient directory<select value={kind} onChange={e=>{setKind(e.target.value);setRecipient(null);}}><option value="customers">Customers</option><option value="technicians">Technicians</option></select></label><DirectoryPicker key={kind} api={directories} kind={kind} selected={recipient} onSelect={setRecipient} disabled={busy}/><div className="asset-fields"><label>Title *<input required maxLength={200} value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/></label><label>Channel<input readOnly value="IN_APP"/></label><label>Message *<textarea required maxLength={2000} value={draft.message} onChange={e=>setDraft(d=>({...d,message:e.target.value}))}/></label><label>Optional schedule (UTC, not local time)<input type="datetime-local" step="1" value={draft.scheduledAt} onChange={e=>setDraft(d=>({...d,scheduledAt:e.target.value}))}/></label></div></fieldset><ErrorState error={error}/><div className="page-actions"><button type="button" className="secondary-btn" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy||!recipient}>{busy?'Creating...':'Create notification'}</button></div></form>;
}
export function NotificationsPage({api,directories,user}){
 const [page,setPage]=useState(0),[status,setStatus]=useState(''),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[busy,setBusy]=useState(false),[composing,setComposing]=useState(false),[revision,setRevision]=useState(0),[notice,setNotice]=useState('');
 const allowed=isAdmin(user);
 useEffect(()=>{if(!allowed||composing||selected)return;let current=true;setData(null);setError(null);setLoading(true);api.list({page,size:10,status,q}).then(v=>{if(current)setData(v);}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[api,allowed,composing,selected,page,status,q,revision]);
 const read=async row=>{setBusy(true);setError(null);setNotice('');try{const confirmed=await api.read(row.id);setNotice('Notification #'+confirmed.id+' marked '+confirmed.status+'.');setData(null);setRevision(v=>v+1);}catch(e){setData(null);setError(e);}finally{setBusy(false);}};
 const markAll=async()=>{const unread=(data?.items||[]).filter(row=>row.recipientUserId===user.userId&&row.status!=='READ');setBusy(true);try{for(const row of unread)await api.read(row.id);setNotice(`${unread.length} notifications marked read.`);setRevision(v=>v+1);}catch(e){setError(e);}finally{setBusy(false);}};
 if(!allowed)return <p role="alert">Access denied. Administrator role required.</p>;
 if(composing)return <ComposeNotification api={api} directories={directories} onClose={()=>setComposing(false)} onCreated={row=>{setNotice('Notification #'+row.id+' created with status '+row.status+'. View the recipient’s inbox when due; it is not added to your inbox.');setComposing(false);}}/>;
 if(selected)return <><div className="page-header"><div><div className="eyebrow">COMMUNICATION</div><h1>Notification Details</h1></div><div className="page-actions"><button className="secondary-btn" onClick={()=>setSelected(null)}>Back</button>{selected.recipientUserId===user.userId&&selected.status!=='READ'&&<button className="primary-btn" disabled={busy} onClick={()=>read(selected)}>Mark read</button>}</div></div><section className="asset-form panel"><dl>{Object.entries(selected).map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{['status','channel'].includes(key)?<StatusChip value={value}/>:displayValue(value)}</dd></React.Fragment>)}</dl></section></>;
 return <><div className="page-header"><div><div className="eyebrow">COMMUNICATION</div><h1>My notification inbox</h1><p>Only notifications addressed to your signed-in account and due now.</p></div><div className="page-actions"><button className="secondary-btn" disabled={busy||loading} onClick={markAll}>Mark All Read</button><button className="primary-btn" disabled={busy} onClick={()=>{setNotice('');setComposing(true);}}>Compose</button></div></div>{notice&&<p role="status">{notice}</p>}<section className="asset-form panel"><div className="table-controls"><label>Search<input value={q} onChange={e=>{setQ(e.target.value);setPage(0);}} placeholder="Search notifications"/></label><label>Status<select disabled={busy} value={status} onChange={e=>{setData(null);setStatus(e.target.value);setPage(0);}}><option value="">All</option>{notificationStatuses.map(s=><option key={s}>{s}</option>)}</select></label><button className="secondary-btn" disabled={busy||loading} onClick={()=>setRevision(v=>v+1)}>Refresh inbox</button></div><ErrorState error={error}/>{loading?<p role="status">Loading inbox...</p>:data&&<NotificationTable items={data.items} onOpen={setSelected}/>}<Pager data={data} page={page} busy={loading||busy} onPage={p=>{setData(null);setPage(p);}}/></section></>;
}
