import React,{useEffect,useState} from 'react';
import {notificationStatuses} from './api/notifications.js';
import {isAdmin} from './api/services.js';
import {DirectoryPicker,Pager} from './workflowModules.jsx';
import {ErrorState,displayValue} from './assetModules.jsx';
export function NotificationTable({items,userId,busy,onRead}){return <div className="asset-table"><table><thead><tr>{['Title','Message','Channel','Status','Scheduled (UTC)','Sent (UTC)','Read (UTC)','Action'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{items.map(row=><tr key={row.id}><td>{row.title}</td><td style={{whiteSpace:'pre-wrap',minWidth:200,maxWidth:400,overflowWrap:'anywhere'}}>{row.message}</td><td>{row.channel}</td><td>{row.status}</td><td>{displayValue(row.scheduledAt)}</td><td>{displayValue(row.sentAt)}</td><td>{displayValue(row.readAt)}</td><td>{row.recipientUserId===userId&&row.status!=='READ'&&<button className="secondary-btn" disabled={busy} onClick={()=>onRead(row)}>Mark read</button>}</td></tr>)}</tbody></table></div>;}
export function ComposeNotification({api,directories,onClose,onCreated}){
 const [kind,setKind]=useState('customers'),[recipient,setRecipient]=useState(null),[draft,setDraft]=useState({title:'',message:'',scheduledAt:''}),[busy,setBusy]=useState(false),[error,setError]=useState(null);
 const submit=async e=>{e.preventDefault();setBusy(true);setError(null);try{onCreated(await api.create(draft,recipient));}catch(e){setError(e);}finally{setBusy(false);}};
 return <form className="asset-form panel" onSubmit={submit}><h2>Compose in-app notification</h2><p>Create a notification record for a selected customer or technician. It appears in their inbox when due; this is not external delivery or a sent-history view.</p><fieldset disabled={busy}><label>Recipient directory<select value={kind} onChange={e=>{setKind(e.target.value);setRecipient(null);}}><option value="customers">Customers</option><option value="technicians">Technicians</option></select></label><DirectoryPicker key={kind} api={directories} kind={kind} selected={recipient} onSelect={setRecipient} disabled={busy}/><div className="asset-fields"><label>Title *<input required maxLength={200} value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/></label><label>Channel<input readOnly value="IN_APP"/></label><label>Message *<textarea required maxLength={2000} value={draft.message} onChange={e=>setDraft(d=>({...d,message:e.target.value}))}/></label><label>Optional schedule (UTC, not local time)<input type="datetime-local" step="1" value={draft.scheduledAt} onChange={e=>setDraft(d=>({...d,scheduledAt:e.target.value}))}/></label></div></fieldset><ErrorState error={error}/><div className="page-actions"><button type="button" className="secondary-btn" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy||!recipient}>{busy?'Creating...':'Create notification'}</button></div></form>;
}
export function NotificationsPage({api,directories,user}){
 const [page,setPage]=useState(0),[status,setStatus]=useState(''),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[busy,setBusy]=useState(false),[composing,setComposing]=useState(false),[revision,setRevision]=useState(0),[notice,setNotice]=useState('');
 const allowed=isAdmin(user);
 useEffect(()=>{if(!allowed||composing)return;let current=true;setData(null);setError(null);setLoading(true);api.list({page,size:20,status}).then(v=>{if(current)setData(v);}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[api,allowed,composing,page,status,revision]);
 const read=async row=>{setBusy(true);setError(null);setNotice('');try{const confirmed=await api.read(row.id);setNotice('Notification #'+confirmed.id+' marked '+confirmed.status+'.');setData(null);setRevision(v=>v+1);}catch(e){setData(null);setError(e);}finally{setBusy(false);}};
 if(!allowed)return <p role="alert">Access denied. Administrator role required.</p>;
 if(composing)return <ComposeNotification api={api} directories={directories} onClose={()=>setComposing(false)} onCreated={row=>{setNotice('Notification #'+row.id+' created with status '+row.status+'. View the recipient’s inbox when due; it is not added to your inbox.');setComposing(false);}}/>;
 return <><div className="page-header"><div><div className="eyebrow">COMMUNICATION</div><h1>My notification inbox</h1><p>Only notifications addressed to your signed-in account and due now. No sent-history or unread total is provided.</p></div><button className="primary-btn" disabled={busy} onClick={()=>{setNotice('');setComposing(true);}}>Compose</button></div>{notice&&<p role="status">{notice}</p>}<section className="asset-form panel"><label>Status<select disabled={busy} value={status} onChange={e=>{setData(null);setStatus(e.target.value);setPage(0);}}><option value="">All</option>{notificationStatuses.map(s=><option key={s}>{s}</option>)}</select></label><button className="secondary-btn" disabled={busy||loading} onClick={()=>setRevision(v=>v+1)}>Refresh inbox</button><ErrorState error={error}/>{loading?<p role="status">Loading inbox...</p>:data?.items.length===0?<p>No notifications in this inbox page.</p>:data&&<NotificationTable items={data.items} userId={user.userId} busy={busy} onRead={read}/>}<Pager data={data} page={page} busy={loading||busy} onPage={p=>{setData(null);setPage(p);}}/></section></>;
}
