import React,{useEffect,useState}from'react';
function ErrorState({error}){return error?<p role="alert" className="error-text">{error.message||String(error)}</p>:null;}
const emptyTemplate={name:'',description:'',active:true,serviceTypes:[]};
const emptyItem={label:'',description:'',required:true,sortOrder:0,inputType:'CHECKBOX'};
export function ChecklistTemplatesPage({api}){
 const[data,setData]=useState([]),[selected,setSelected]=useState(null),[draft,setDraft]=useState(emptyTemplate),[item,setItem]=useState(emptyItem),[loading,setLoading]=useState(true),[error,setError]=useState(null),[notice,setNotice]=useState('');
 const load=()=>{setLoading(true);setError(null);api.templates().then(setData).catch(setError).finally(()=>setLoading(false));};
 useEffect(load,[]);
 const edit=row=>{setSelected(row);setDraft({name:row.name,description:row.description||'',active:row.active,serviceTypes:row.serviceTypes||[]});};
 const save=async e=>{e.preventDefault();setError(null);try{await api.saveTemplate(draft,selected);setSelected(null);setDraft(emptyTemplate);setNotice('Checklist template saved.');load();}catch(err){setError(err);}};
 const saveItem=async e=>{e.preventDefault();if(!selected)return;setError(null);try{await api.addItem(selected.id,item);setItem(emptyItem);setNotice('Checklist item added.');load();}catch(err){setError(err);}};
 const toggleType=value=>setDraft(current=>({...current,serviceTypes:current.serviceTypes.includes(value)?current.serviceTypes.filter(item=>item!==value):[...current.serviceTypes,value]}));
 return <><div className="page-header"><div><div className="eyebrow">SERVICE QUALITY</div><h1>Checklist Templates</h1><p>Create reusable technician checklists by service type. Technicians complete job checklists from these templates.</p></div><button className="secondary-btn" onClick={load}>Refresh</button></div>
 <section className="panel asset-form"><ErrorState error={error}/>{notice&&<p role="status">{notice}</p>}<form onSubmit={save}><h2>{selected?'Edit template':'Create template'}</h2><div className="asset-fields"><label>Name<input value={draft.name} maxLength={160} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Active<select value={String(draft.active)} onChange={e=>setDraft({...draft,active:e.target.value==='true'})}><option value="true">Active</option><option value="false">Inactive</option></select></label></div><label>Description<textarea value={draft.description} maxLength={1000} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="asset-fields">{api.serviceTypes.map(type=><label key={type}><span><input type="checkbox" checked={draft.serviceTypes.includes(type)} onChange={()=>toggleType(type)}/> {type}</span></label>)}</div><button className="primary-btn">Save template</button><button type="button" className="secondary-btn" onClick={()=>{setSelected(null);setDraft(emptyTemplate);}}>New</button></form></section>
 <section className="panel asset-table">{loading?<p>Loading templates...</p>:<table><thead><tr><th>Name</th><th>Status</th><th>Version</th><th>Types</th><th>Items</th><th>Action</th></tr></thead><tbody>{data.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.active?'Active':'Inactive'}</td><td>{row.version}</td><td>{(row.serviceTypes||[]).join(', ')||'All'}</td><td>{row.items?.length||0}</td><td><button className="secondary-btn" onClick={()=>edit(row)}>Open</button></td></tr>)}</tbody></table>}</section>
 {selected&&<section className="panel asset-form"><h2>Items for {selected.name}</h2><form onSubmit={saveItem}><div className="asset-fields"><label>Label<input value={item.label} maxLength={255} onChange={e=>setItem({...item,label:e.target.value})}/></label><label>Type<select value={item.inputType} onChange={e=>setItem({...item,inputType:e.target.value})}>{['CHECKBOX','TEXT','NUMBER','PHOTO_NOTE'].map(v=><option key={v}>{v}</option>)}</select></label><label>Sort<input type="number" value={item.sortOrder} onChange={e=>setItem({...item,sortOrder:e.target.value})}/></label><label>Required<select value={String(item.required)} onChange={e=>setItem({...item,required:e.target.value==='true'})}><option value="true">Required</option><option value="false">Optional</option></select></label></div><label>Description<textarea value={item.description} maxLength={1000} onChange={e=>setItem({...item,description:e.target.value})}/></label><button className="primary-btn">Add item</button></form><div className="asset-table"><table><thead><tr><th>Sort</th><th>Label</th><th>Type</th><th>Required</th><th>Action</th></tr></thead><tbody>{(selected.items||[]).map(row=><tr key={row.id}><td>{row.sortOrder}</td><td>{row.label}</td><td>{row.inputType}</td><td>{String(row.required)}</td><td><button className="secondary-btn" onClick={async()=>{await api.deleteItem(selected.id,row.id);load();}}>Delete</button></td></tr>)}</tbody></table></div></section>}</>;
}
export function TechnicianProfileAdminPage({api}){
 const[id,setId]=useState(''),[profile,setProfile]=useState(null),[files,setFiles]=useState([]),[error,setError]=useState(null),[notice,setNotice]=useState('');
 const load=async()=>{setError(null);try{const p=await api.technicianProfile(id);setProfile(p);setFiles(await api.technicianPrivateAttachments(id));}catch(e){setError(e);}};
 const update=(key,value)=>setProfile(current=>({...current,[key]:value}));
 const save=async e=>{e.preventDefault();setError(null);try{setProfile(await api.updateTechnicianProfile(id,profile));setNotice('Technician profile saved.');}catch(err){setError(err);}};
 return <><div className="page-header"><div><div className="eyebrow">STAFF</div><h1>Technician Profile</h1><p>View/edit approved expanded profile fields and technician-private attachments.</p></div></div><section className="panel asset-form"><ErrorState error={error}/>{notice&&<p>{notice}</p>}<label>Technician profile ID<input value={id} onChange={e=>setId(e.target.value)} /></label><button className="secondary-btn" onClick={load}>Load technician</button>{profile&&<form onSubmit={save}><div className="asset-fields">{['assignedArea','specialization','profilePhotoUrl','dateOfBirth','gender','address','emergencyContactName','emergencyContactPhone'].map(key=><label key={key}>{key}<input value={profile[key]||''} onChange={e=>update(key,e.target.value)} /></label>)}</div><button className="primary-btn">Save profile</button></form>}</section>{profile&&<section className="panel asset-table"><h2>Private attachments</h2>{files.length?<table><thead><tr><th>File</th><th>Type</th><th>Size</th><th>Action</th></tr></thead><tbody>{files.map(file=><tr key={file.id}><td>{file.originalFilename}</td><td>{file.contentType}</td><td>{file.fileSize}</td><td><button className="secondary-btn" onClick={async()=>{const r=await api.openTechnicianPrivateAttachment(id,file.id);window.open(URL.createObjectURL(await r.blob()),'_blank');}}>Open</button><button className="secondary-btn" onClick={async()=>{await api.deleteTechnicianPrivateAttachment(id,file.id);await load();}}>Delete</button></td></tr>)}</tbody></table>:<p>No private attachments.</p>}</section>}</>;
}
