import React, { useEffect, useState } from 'react';

const label = value => String(value || '').replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, character => character.toUpperCase());
export function TechnicianApplicationsPage({ api }) {
  const [rows, setRows] = useState([]), [selected, setSelected] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [busy, setBusy] = useState(false), [mode, setMode] = useState('NONE');
  const load = async () => { setLoading(true); try { const page = await api.list(); setRows(page.items || page || []); } catch (value) { setError(value.message || 'Could not load applications.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const update = async action => { setBusy(true); try { await action(); setSelected(null); await load(); } catch (value) { setError(value.message || 'Could not update application.'); } finally { setBusy(false); } };
  const eligible = Boolean(selected && ((selected.status === 'DOCUMENTS_VERIFIED' && ['PROFILE_PHOTO', 'AADHAAR_CARD', 'ADDRESS_PROOF'].every(type => selected.documents?.some(document => document.documentType === type && document.reviewStatus === 'VERIFIED'))) || selected.status === 'MEETING_COMPLETED'));
  const requiredTypes = ['PROFILE_PHOTO', 'AADHAAR_CARD', 'ADDRESS_PROOF'];
  const eligible = Boolean(selected && ((selected.status === 'DOCUMENTS_VERIFIED' && requiredTypes.every(type => selected.documents?.some(document => document.documentType === type && document.reviewStatus === 'VERIFIED'))) || selected.status === 'MEETING_COMPLETED'));
  const saveMeeting = () => { if (mode === 'NONE') return update(() => api.meeting(selected.id, { mode, meetingAt: null, meetingUrl: null, meetingPhone: null, meetingLocation: null, meetingMapUrl: null, notes: null })); const meetingAt = window.prompt('Meeting date/time (ISO format)', ''); if (!meetingAt) return; const meetingUrl = mode === 'GOOGLE_MEET' ? window.prompt('Google Meet URL', '') : null; const meetingPhone = mode === 'PHONE' ? window.prompt('Phone number', '') : null; const meetingLocation = mode === 'PHYSICAL' ? window.prompt('Meeting address', '') : null; const meetingMapUrl = mode === 'PHYSICAL' ? window.prompt('Optional Google Maps URL', '') : null; return update(() => api.meeting(selected.id, { mode, meetingAt, meetingUrl, meetingPhone, meetingLocation, meetingMapUrl, notes: null })); };
  return <><div className="page-header"><div><div className="eyebrow">ADMINISTRATION</div><h1>Technician Applications</h1><p>Review documents, meetings, and final access approval.</p></div><button className="secondary-btn" onClick={load}>Refresh</button></div>{error && <p role="alert" className="error-text">{error}</p>}<section className="panel table-panel"><table><thead><tr><th>Applicant</th><th>Email</th><th>Status</th><th>Documents</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan="5">Loading...</td></tr> : rows.map(row => <tr key={row.id}><td>{row.fullName}</td><td>{row.email}</td><td>{label(row.status)}</td><td>{row.documents?.filter(document => document.reviewStatus === 'VERIFIED').length || 0}/{row.documents?.length || 0} verified</td><td><button className="secondary-btn" onClick={() => setSelected(row)}>Review</button></td></tr>)}</tbody></table></section>{selected && <section className="panel asset-form"><div className="page-actions"><h2>Review {selected.fullName}</h2><button className="secondary-btn" onClick={() => setSelected(null)}>Close</button></div><p>Status: <b>{label(selected.status)}</b></p><h3>Documents</h3>{(selected.documents || []).map(document => <div className="row" key={document.id}><span>{document.documentType} · {label(document.reviewStatus)}</span><span><button className="secondary-btn" disabled={busy} onClick={() => update(() => api.reviewDocument(selected.id, document.id, 'VERIFIED'))}>Verify</button> <button className="secondary-btn" disabled={busy} onClick={() => update(() => api.reviewDocument(selected.id, document.id, 'REJECTED', window.prompt('Rejection reason', '') || 'Rejected by Admin'))}>Reject</button></span></div>)}<div className="asset-fields"><label>Meeting mode<select value={mode} onChange={event => setMode(event.target.value)}><option value="NONE">No meeting</option><option value="GOOGLE_MEET">Google Meet</option><option value="PHONE">Phone call</option><option value="PHYSICAL">Physical meeting</option></select></label></div><button className="primary-btn" disabled={busy} onClick={() => update(() => api.meeting(selected.id, { mode, meetingAt: null, meetingUrl: null, meetingPhone: null, meetingLocation: null, meetingMapUrl: null, notes: null }))}>Save verification decision</button>{['MEETING_SCHEDULED','MEETING_REQUIRED'].includes(selected.status) && <button className="secondary-btn" disabled={busy} onClick={() => update(() => api.completeMeeting(selected.id))}>Mark meeting complete</button>}<button className="primary-btn" disabled={busy} onClick={() => update(() => api.review(selected.id, 'APPROVED'))}>Final approve</button><button className="secondary-btn" disabled={busy} onClick={() => update(() => api.review(selected.id, 'REJECTED', 'Rejected by Admin'))}>Reject application</button></section>}</>;
}
