import React,{useEffect,useState} from 'react';
import {priorities,serviceTypes,statuses,relatedAssets,nextStatuses} from './api/workflow.js';
import {isAdmin} from './api/services.js';
import {ErrorState,displayValue} from './assetModules.jsx';
import './workflow.css';
export function Pager({data,page,onPage,busy}){return <div className="page-actions"><button type="button" className="secondary-btn" disabled={busy||page===0} onClick={()=>onPage(page-1)}>Previous</button><span>Page {page+1}{data?` · ${data.totalElements} results`:''}</span><button type="button" className="secondary-btn" disabled={busy||!data||page+1>=data.totalPages} onClick={()=>onPage(page+1)}>Next</button></div>;}
export function DirectoryPicker({api,kind,selected,onSelect,disabled=false}){
 const [q,setQ]=useState(''),[page,setPage]=useState(0),[data,setData]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 useEffect(()=>{let current=true;setData(null);setLoading(true);setError(null);api.directory(kind,{q,page,size:10,active:true}).then(v=>{if(current)setData(v);}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[api,kind,q,page,revision]);
 const changePage=value=>{setData(null);setPage(value);};
 return <fieldset disabled={disabled} className="workflow-picker"><legend>{kind==='customers'?'Customer':'Technician'} selection</legend>
 <label>Search {kind}<input maxLength={254} value={q} onChange={e=>{setData(null);setQ(e.target.value);setPage(0);}} placeholder="Search by name, email or supported directory fields"/></label>
 {selected&&<p role="status">Selected: {selected.fullName||selected.employeeId||selected.email} <button type="button" className="secondary-btn" onClick={()=>onSelect(null)}>Clear selection</button></p>}
 <ErrorState error={error}/>{error&&<button type="button" className="secondary-btn" onClick={()=>setRevision(v=>v+1)}>Retry directory</button>}
 {loading?<p role="status">Loading directory...</p>:data?.items.length===0?<p>No matching {kind}.</p>:<ul>{data?.items.map(row=><li key={row.customerProfileId??row.technicianProfileId}><button type="button" className="secondary-btn" disabled={!row.active||(kind==='customers'&&row.status!=='ACTIVE')} onClick={()=>onSelect(row)}>{row.fullName||row.employeeId||row.email} · {row.email||'Phone-only account'}{kind==='technicians'?` · ${row.assignedArea||'Area not provided'} · ${row.availabilityStatus}`:` · ${row.status}`}</button></li>)}</ul>}
 <Pager data={data} page={page} onPage={changePage} busy={loading||disabled}/></fieldset>;
}
export function CreateRequest({api,assets,onSaved,onClose}){
 const [customer,setCustomer]=useState(null),[draft,setDraft]=useState({priority:'MEDIUM',serviceType:''}),[buildings,setBuildings]=useState([]),[lifts,setLifts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let current=true;setLoading(true);setBuildings([]);setLifts([]);setError(null);Promise.all([assets.buildings.list(),assets.lifts.list()]).then(([b,l])=>{if(current){setBuildings(b);setLifts(l);}}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[assets,revision]);
 const related=relatedAssets(customer,buildings,lifts,draft.buildingId);
 const submit=async e=>{e.preventDefault();setBusy(true);setError(null);try{onSaved(await api.create(draft,customer,buildings,lifts));}catch(e){setError(e);}finally{setBusy(false);}};
 return <form className="asset-form panel" onSubmit={submit}><h2>Create service request</h2><p>Select an active customer, then their building and lift. The backend revalidates ownership and eligibility.</p>
 <DirectoryPicker api={api} kind="customers" selected={customer} disabled={busy} onSelect={c=>{setCustomer(c);setDraft(d=>({...d,buildingId:'',liftId:''}));}}/>
 {loading&&<p role="status">Loading assets...</p>}<ErrorState error={error}/>{error&&<button type="button" className="secondary-btn" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Reload assets</button>}
 <fieldset disabled={busy||loading}><div className="asset-fields"><label>Building *<select required value={draft.buildingId||''} onChange={e=>setDraft(d=>({...d,buildingId:e.target.value,liftId:''}))}><option value="">Select customer building</option>{related.buildings.map(b=><option key={b.id} value={b.id}>{b.buildingName}</option>)}</select></label>
 <label>Lift *<select required value={draft.liftId||''} onChange={e=>setDraft(d=>({...d,liftId:e.target.value}))}><option value="">Select building lift</option>{related.lifts.map(l=><option key={l.id} value={l.id}>{l.name} · {l.currentStatus}</option>)}</select></label>
 <label>Service type *<select required value={draft.serviceType} onChange={e=>setDraft(d=>({...d,serviceType:e.target.value}))}><option value="">Select type</option>{serviceTypes.map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Priority *<select value={draft.priority} onChange={e=>setDraft(d=>({...d,priority:e.target.value}))}>{priorities.map(s=><option key={s}>{s}</option>)}</select></label>
 {[['title','Title',200,true],['description','Description',null,true],['issueCategory','Issue category',100],['customerRemarks','Customer remarks',2000],['internalAdminNotes','Internal admin notes',2000],['preferredVisitDate','Preferred visit date',null,false,'date'],['preferredTimeSlot','Preferred time slot',80],['estimatedCompletionMinutes','Estimated completion minutes',null,false,'number']].map(([key,label,max,required,type])=><label key={key}>{label}{required?' *':''}{['description','customerRemarks','internalAdminNotes'].includes(key)?<textarea required={required} maxLength={max??undefined} value={draft[key]??''} onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))}/>:<input required={required} maxLength={max??undefined} type={type||'text'} min={type==='number'?0:undefined} max={type==='number'?2147483647:undefined} step={type==='number'?1:undefined} value={draft[key]??''} onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))}/>}</label>)}</div></fieldset>
 {!loading&&customer&&!related.buildings.length&&<p>No active buildings for this customer.</p>}{draft.buildingId&&!related.lifts.length&&<p>No active lifts for this building.</p>}
 <div className="page-actions"><button type="button" className="secondary-btn" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy||loading||!customer||!related.lifts.length}>{busy?'Creating...':'Create request'}</button></div></form>;
}
const fields=(record,keys)=><dl>{keys.map(key=><React.Fragment key={key}><dt>{key}</dt><dd>{displayValue(record[key])}</dd></React.Fragment>)}</dl>;
export function RequestDetail({detail}){
 return <><h2>{detail.request.serviceId} · {detail.request.title}</h2>{fields(detail.request,['id','customerProfileId','liftId','status','priority','serviceType','description','issueCategory','customerRemarks','technicianRemarks','internalAdminNotes','preferredVisitDate','preferredTimeSlot','estimatedCompletionMinutes','serviceRequestedAt','completedAt'])}
 <h3>Active assignment</h3>{detail.activeAssignment?fields(detail.activeAssignment,['id','technicianProfileId','status','assignedAt','acceptedAt','notes']):<p>No active assignment.</p>}
 <h3>Status history</h3>{detail.history.length?<ol>{detail.history.map(h=><li key={h.id}>{h.fromStatus??'Created'} ? {h.toStatus} · {displayValue(h.changedAt)}<p>{displayValue(h.notes)}</p></li>)}</ol>:<p>No status history returned.</p>}
 <h3>Service report (read only)</h3>{detail.report?fields(detail.report,['id','assignmentId','diagnosis','workPerformed','testingResult','completionNotes','createdAt','updatedAt']):<p>No service report returned.</p>}</>;
}
export function DetailPage({id,api,onBack}){
 const [detail,setDetail]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[technician,setTechnician]=useState(null),[notes,setNotes]=useState(''),[toStatus,setToStatus]=useState(''),[statusNotes,setStatusNotes]=useState('');
 useEffect(()=>{let current=true;setDetail(null);setError(null);setLoading(true);api.detail(id).then(d=>{if(current)setDetail(d);}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[api,id,revision]);
 const mutate=async action=>{setBusy(true);setError(null);try{const returned=await action();setDetail(returned);setTechnician(null);setNotes('');setStatusNotes('');setToStatus('');}catch(e){setDetail(null);setError(e);}finally{setBusy(false);}};
 const terminal=detail&&['COMPLETED','CANCELLED'].includes(detail.request.status);
 return <section className="asset-form panel"><div className="page-actions"><button className="secondary-btn" disabled={busy} onClick={onBack}>Back to requests</button><button className="secondary-btn" disabled={busy||loading} onClick={()=>setRevision(v=>v+1)}>Reload detail</button></div><ErrorState error={error}/>{loading?<p role="status">Loading request...</p>:detail&&<><RequestDetail detail={detail}/>{!terminal&&<><h3>Assign / reassign technician</h3><p>Reassignment releases the current assignment. An advanced reassignment must be accepted in the technician client before further progress.</p><DirectoryPicker api={api} kind="technicians" selected={technician} onSelect={setTechnician} disabled={busy}/><label>Assignment notes<textarea maxLength={2000} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary-btn" disabled={busy||!technician} onClick={()=>{if(window.confirm('Assign selected technician and release any current assignment?'))mutate(()=>api.assign(detail,technician,notes));}}>Assign technician</button>
 <h3>Update status</h3><p>Actions depend on the latest backend state. Completion requires the active assignment’s valid technician report. Reports and the technician acceptance endpoint are not available here.</p><form onSubmit={e=>{e.preventDefault();if(window.confirm('Submit status '+toStatus+'?'))mutate(()=>api.status(detail,toStatus,statusNotes));}}><label>Next status<select required disabled={busy} value={toStatus} onChange={e=>setToStatus(e.target.value)}><option value="">Select action</option>{nextStatuses(detail).map(s=><option key={s}>{s}</option>)}</select></label><label>Notes / cancellation reason<textarea disabled={busy} maxLength={2000} required={['CANCELLED','WAITING_FOR_PARTS'].includes(toStatus)} value={statusNotes} onChange={e=>setStatusNotes(e.target.value)}/></label><button className="primary-btn" disabled={busy||!toStatus}>Submit status</button></form></>}</>}</section>;
}
export function WorkflowPage({api,assets,user}){
 const [page,setPage]=useState(0),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[data,setData]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[view,setView]=useState(null);
 const allowed=isAdmin(user);
 useEffect(()=>{if(!allowed||view)return;let current=true;setData(null);setError(null);setLoading(true);api.list({page,size:20,status,priority}).then(d=>{if(current)setData(d);}).catch(e=>{if(current)setError(e);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[api,allowed,view,page,status,priority,revision]);
 if(!allowed)return <p role="alert">Access denied. Administrator role required.</p>;
 if(view==='create')return <CreateRequest api={api} assets={assets} onClose={()=>setView(null)} onSaved={d=>setView(d.request.id)}/>;
 if(view)return <DetailPage key={view} id={view} api={api} onBack={()=>setView(null)}/>;
 return <><div className="page-header"><div><div className="eyebrow">SERVICE OPERATIONS</div><h1>Service requests</h1></div><button className="primary-btn" onClick={()=>setView('create')}>Create request</button></div><section className="asset-form panel"><div className="asset-fields">{[['Status',statuses,status,setStatus],['Priority',priorities,priority,setPriority]].map(([label,options,value,set])=><label key={label}>{label}<select value={value} onChange={e=>{setData(null);set(e.target.value);setPage(0);}}><option value="">All</option>{options.map(s=><option key={s}>{s}</option>)}</select></label>)}</div><button className="secondary-btn" disabled={loading} onClick={()=>setRevision(v=>v+1)}>Refresh requests</button><ErrorState error={error}/>{loading?<p role="status">Loading requests...</p>:data?.items.length===0?<p>No service requests found.</p>:<div className="asset-table"><table><thead><tr><th>Request</th><th>Title</th><th>Status</th><th>Priority</th><th>Action</th></tr></thead><tbody>{data?.items.map(r=><tr key={r.id}><td>{r.serviceId}</td><td>{r.title}</td><td>{r.status}</td><td>{r.priority}</td><td><button className="secondary-btn" onClick={()=>setView(r.id)}>View detail</button></td></tr>)}</tbody></table></div>}<Pager data={data} page={page} onPage={p=>{setData(null);setPage(p);}} busy={loading}/></section></>;
}
