import React, { useEffect, useState } from 'react';
import { priorities, serviceTypes, statuses, relatedAssets, nextStatuses } from './api/workflow.js';
import { isAdmin } from './api/services.js';
import { ErrorState, displayValue } from './assetModules.jsx';
import { AvailabilityDot, DataTable, PagerButtons, PriorityChip, StatusChip, detailPageSize } from './uiPatterns.jsx';
import './workflow.css';

export function Pager({ data, page, onPage, busy }) {
  return <PagerButtons page={page} totalPages={data?.totalPages} totalItems={data?.totalElements} onPage={onPage} busy={busy} />;
}

export function DirectoryPicker({ api, kind, selected, onSelect, disabled = false }) {
  const [q, setQ] = useState(''), [page, setPage] = useState(0), [data, setData] = useState(null), [error, setError] = useState(null), [loading, setLoading] = useState(true), [revision, setRevision] = useState(0);
  useEffect(() => { let current = true; setData(null); setLoading(true); setError(null); api.directory(kind, { q, page, size: 10, active: true }).then(value => { if (current) setData(value); }).catch(value => { if (current) setError(value); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [api, kind, q, page, revision]);
  const changePage = value => { setData(null); setPage(value); };
  const needsSearch = kind === 'customers' && !q.trim();
  return <fieldset disabled={disabled} className="workflow-picker"><legend>{kind === 'customers' ? 'Customer' : 'Technician'} selection</legend>
    <label>Search {kind}<input maxLength={254} value={q} onChange={event => { setData(null); setQ(event.target.value); setPage(0); }} placeholder="Search by name, email or supported directory fields" /></label>
    {selected && <p role="status">Selected: {selected.fullName || selected.employeeId || selected.email} <button type="button" className="secondary-btn" onClick={() => onSelect(null)}>Clear selection</button></p>}
    <ErrorState error={error} />{error && <button type="button" className="secondary-btn" onClick={() => setRevision(value => value + 1)}>Retry directory</button>}
    {needsSearch ? <p className="directory-hint">Search to find a customer.</p> : loading ? <p role="status">Loading directory...</p> : data?.items.length === 0 ? <p>No matching {kind}.</p> : kind === 'technicians' ? <select value={selected?.technicianProfileId || ''} onChange={event => onSelect(data.items.find(row => String(row.technicianProfileId) === event.target.value) || null)}><option value="">Select technician</option>{data.items.map(row => <option key={row.technicianProfileId} value={row.technicianProfileId}>{row.fullName || row.employeeId || row.email || `Technician #${row.technicianProfileId}`}</option>)}</select> : <ul>{data?.items.map(row => <li key={row.customerProfileId ?? row.technicianProfileId}><button type="button" className="secondary-btn" disabled={!row.active || (kind === 'customers' && row.status !== 'ACTIVE')} onClick={() => onSelect(row)}>{row.fullName || row.email || `Customer #${row.customerProfileId}`}</button></li>)}</ul>}
    {kind === 'technicians' && selected && <p className="directory-availability"><AvailabilityDot value={selected.availabilityStatus} /></p>}
    <Pager data={data} page={page} onPage={changePage} busy={loading || disabled} /></fieldset>;
}

export function CreateRequest({ api, assets, onSaved, onClose }) {
  const [customer, setCustomer] = useState(null), [draft, setDraft] = useState({ priority: 'MEDIUM', serviceType: '' }), [buildings, setBuildings] = useState([]), [lifts, setLifts] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(null), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0);
  useEffect(() => { let current = true; setLoading(true); setBuildings([]); setLifts([]); setError(null); Promise.all([assets.buildings.list(), assets.lifts.list()]).then(([b, l]) => { if (current) { setBuildings(b); setLifts(l); } }).catch(value => { if (current) setError(value); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [assets, revision]);
  const related = relatedAssets(customer, buildings, lifts, draft.buildingId);
  const submit = async event => { event.preventDefault(); setBusy(true); setError(null); try { onSaved(await api.create(draft, customer, buildings, lifts)); } catch (value) { setError(value); } finally { setBusy(false); } };
  const installation = draft.serviceType === 'INSTALLATION';
  return <form className="asset-form panel" onSubmit={submit}><div className="page-actions"><button type="button" className="secondary-btn" disabled={busy} onClick={onClose}>Back to service requests</button></div><h2>Create service request</h2><p>Select an active customer. Lift is optional only for installation requests; the backend revalidates ownership and eligibility.</p>
    <DirectoryPicker api={api} kind="customers" selected={customer} disabled={busy} onSelect={value => { setCustomer(value); setDraft(current => ({ ...current, buildingId: '', liftId: '' })); }} />
    {loading && <p role="status">Loading assets...</p>}<ErrorState error={error} />{error && <button type="button" className="secondary-btn" disabled={busy} onClick={() => setRevision(value => value + 1)}>Reload assets</button>}
    <fieldset disabled={busy || loading}><div className="asset-fields"><label>Building{installation ? '' : ' *'}<select required={!installation} value={draft.buildingId || ''} onChange={event => setDraft(current => ({ ...current, buildingId: event.target.value, liftId: '' }))}><option value="">Select customer building</option>{related.buildings.map(building => <option key={building.id} value={building.id}>{building.buildingName}</option>)}</select></label>
      <label>Lift{installation ? ' (optional)' : ' *'}<select required={!installation} value={draft.liftId || ''} onChange={event => setDraft(current => ({ ...current, liftId: event.target.value }))}><option value="">{installation ? 'No existing lift / installation request' : 'Select building lift'}</option>{related.lifts.map(lift => <option key={lift.id} value={lift.id}>{lift.name} - {lift.currentStatus}</option>)}</select></label>
      <label>Service type *<select required value={draft.serviceType} onChange={event => setDraft(current => ({ ...current, serviceType: event.target.value }))}><option value="">Select type</option>{serviceTypes.map(value => <option key={value}>{value}</option>)}</select></label>
      <label>Priority *<select value={draft.priority} onChange={event => setDraft(current => ({ ...current, priority: event.target.value }))}>{priorities.map(value => <option key={value}>{value}</option>)}</select></label>
      {[['title', 'Title', 200, true], ['description', 'Description', null, true], ['issueCategory', 'Issue category', 100], ['customerRemarks', 'Customer remarks', 2000], ['internalAdminNotes', 'Internal admin notes', 2000], ['preferredVisitDate', 'Preferred visit date', null, false, 'date'], ['preferredTimeSlot', 'Preferred time slot', 80], ['estimatedCompletionMinutes', 'Estimated completion minutes', null, false, 'number']].map(([key, label, max, required, type]) => <label key={key}>{label}{required ? ' *' : ''}{['description', 'customerRemarks', 'internalAdminNotes'].includes(key) ? <textarea required={required} maxLength={max ?? undefined} value={draft[key] ?? ''} onChange={event => setDraft(current => ({ ...current, [key]: event.target.value }))} /> : <input required={required} maxLength={max ?? undefined} type={type || 'text'} min={type === 'number' ? 0 : undefined} max={type === 'number' ? 2147483647 : undefined} step={type === 'number' ? 1 : undefined} value={draft[key] ?? ''} onChange={event => setDraft(current => ({ ...current, [key]: event.target.value }))} />}</label>)}</div></fieldset>
    {!loading && customer && !related.buildings.length && <p>No active buildings for this customer.</p>}{draft.buildingId && !related.lifts.length && !installation && <p>No active lifts for this building.</p>}
    <div className="page-actions"><button type="button" className="secondary-btn" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy || loading || !customer || (!installation && !related.lifts.length)}>{busy ? 'Creating...' : 'Create request'}</button></div></form>;
}

const fields = (record, keys) => <dl>{keys.map(key => <React.Fragment key={key}><dt>{key}</dt><dd>{['status','currentStatus'].includes(key) ? <StatusChip value={record[key]} /> : key === 'priority' ? <PriorityChip value={record[key]} /> : displayValue(record[key])}</dd></React.Fragment>)}</dl>;

function PagedDetailTable({ title, columns, rows, empty }) {
  const [page, setPage] = useState(0);
  const totalPages = Math.max(1, Math.ceil((rows?.length || 0) / detailPageSize));
  const safePage = Math.min(page, totalPages - 1);
  const items = (rows || []).slice(safePage * detailPageSize, safePage * detailPageSize + detailPageSize);
  return <section className="detail-table-section"><div className="panel-heading"><div><h3>{title}</h3><span>{rows?.length || 0} records</span></div></div><DataTable columns={columns} rows={items} empty={empty}/><PagerButtons page={safePage} totalPages={totalPages} totalItems={rows?.length || 0} pageSize={detailPageSize} onPage={setPage}/></section>;
}

function RequestEngagement({ attachments = [], feedback = null, error = null, loading = false, busy = false, onOpenAttachment, onDeleteAttachment }) {
  return <><ErrorState error={error} />{loading ? <p role="status">Loading attachments and feedback...</p> : <PagedDetailTable title="Attachments" empty="No customer attachments returned." rows={attachments} columns={[{key:'originalFilename',label:'File'},{key:'contentType',label:'Type'},{key:'fileSize',label:'Size',render:r=>displayValue(r.fileSize)},{key:'createdAt',label:'Uploaded',render:r=>displayValue(r.createdAt)},{key:'actions',label:'Actions',render:r=><span className="table-actions"><button type="button" className="secondary-btn" disabled={busy} onClick={() => onOpenAttachment(r)}>Open</button><button type="button" className="secondary-btn" disabled={busy} onClick={() => onDeleteAttachment(r)}>Delete</button></span>}]} />}
    <PagedDetailTable title="Customer feedback" empty="No customer feedback returned." rows={feedback ? [feedback] : []} columns={[{key:'rating',label:'Rating'},{key:'comment',label:'Comment'},{key:'createdAt',label:'Created',render:r=>displayValue(r.createdAt)},{key:'updatedAt',label:'Updated',render:r=>displayValue(r.updatedAt)}]} /></>;
}

export function RequestDetail({ detail, attachments = [], feedback = null, engagementError = null, engagementLoading = false, engagementBusy = false, onOpenAttachment, onDeleteAttachment }) {
  return <><h2>{detail.request.serviceId} - {detail.request.title}</h2>{fields(detail.request, ['id', 'customerProfileId', 'liftId', 'status', 'priority', 'serviceType', 'description', 'issueCategory', 'customerRemarks', 'technicianRemarks', 'internalAdminNotes', 'preferredVisitDate', 'preferredTimeSlot', 'estimatedCompletionMinutes', 'serviceRequestedAt', 'completedAt'])}
    <h3>Active assignment</h3>{detail.activeAssignment ? fields(detail.activeAssignment, ['id', 'technicianProfileId', 'status', 'assignedAt', 'acceptedAt', 'notes']) : <p>No active assignment.</p>}
    <PagedDetailTable title="Status history" empty="No status history returned." rows={detail.history} columns={[{key:'fromStatus',label:'From',render:r=>r.fromStatus ? <StatusChip value={r.fromStatus}/> : 'Created'},{key:'toStatus',label:'To',render:r=><StatusChip value={r.toStatus}/>},{key:'changedAt',label:'Changed',render:r=>displayValue(r.changedAt)},{key:'notes',label:'Notes',render:r=>displayValue(r.notes)}]} />
    <PagedDetailTable title="Reports" empty="No service report returned." rows={detail.report ? [detail.report] : []} columns={[{key:'id',label:'ID'},{key:'assignmentId',label:'Assignment'},{key:'diagnosis',label:'Diagnosis'},{key:'workPerformed',label:'Work performed'},{key:'testingResult',label:'Testing'},{key:'createdAt',label:'Created',render:r=>displayValue(r.createdAt)}]} />
    <RequestEngagement attachments={attachments} feedback={feedback} error={engagementError} loading={engagementLoading} busy={engagementBusy} onOpenAttachment={onOpenAttachment} onDeleteAttachment={onDeleteAttachment} /></>;
}

function VisitSummary({ visits }) {
  return <PagedDetailTable title="Visits" empty="No visit scheduled yet." rows={visits} columns={[{key:'serviceId',label:'Service'},{key:'status',label:'Status',render:r=><StatusChip value={r.status}/>},{key:'scheduledDate',label:'Date'},{key:'time',label:'Time',render:r=>`${String(r.startTime).slice(0,5)}-${String(r.endTime).slice(0,5)}`},{key:'technicianProfileId',label:'Technician',render:r=>`#${r.technicianProfileId}`},{key:'notes',label:'Notes',render:r=>displayValue(r.notes)}]} />;
}

function VisitScheduler({ detail, visits, visitApi, onSaved, busy }) {
  const assignment = detail.activeAssignment, active = visits.some(visit => ['SCHEDULED', 'IN_PROGRESS'].includes(visit.status));
  const [draft, setDraft] = useState({ scheduledDate: '', startTime: '', endTime: '', notes: '' }), [error, setError] = useState(null), [saving, setSaving] = useState(false);
  if (!assignment) return <p>Assign a technician before scheduling a visit.</p>;
  if (active) return <p>An active or upcoming visit already exists for this request.</p>;
  const submit = async event => { event.preventDefault(); setSaving(true); setError(null); try { await visitApi.create({ ...draft, serviceRequestId: detail.request.id, technicianProfileId: assignment.technicianProfileId }); setDraft({ scheduledDate: '', startTime: '', endTime: '', notes: '' }); onSaved(); } catch (value) { setError(value); } finally { setSaving(false); } };
  return <form className="workflow-picker" onSubmit={submit}><legend>Schedule replacement / next visit</legend><ErrorState error={error} /><fieldset disabled={busy || saving}><div className="asset-fields"><label>Date<input required type="date" value={draft.scheduledDate} onChange={event => setDraft(current => ({ ...current, scheduledDate: event.target.value }))} /></label><label>Start<input required type="time" value={draft.startTime} onChange={event => setDraft(current => ({ ...current, startTime: event.target.value }))} /></label><label>End<input required type="time" value={draft.endTime} onChange={event => setDraft(current => ({ ...current, endTime: event.target.value }))} /></label></div><label>Notes<textarea maxLength={2000} value={draft.notes} onChange={event => setDraft(current => ({ ...current, notes: event.target.value }))} /></label><button className="primary-btn" disabled={saving}>{saving ? 'Scheduling...' : 'Schedule visit'}</button></fieldset></form>;
}

export function DetailPage({ id, api, visits, onBack }) {
  const [detail, setDetail] = useState(null), [visitData, setVisitData] = useState([]), [attachments, setAttachments] = useState([]), [feedback, setFeedback] = useState(null), [error, setError] = useState(null), [visitError, setVisitError] = useState(null), [engagementError, setEngagementError] = useState(null), [loading, setLoading] = useState(true), [engagementLoading, setEngagementLoading] = useState(false), [engagementBusy, setEngagementBusy] = useState(false), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0), [technician, setTechnician] = useState(null), [notes, setNotes] = useState(''), [toStatus, setToStatus] = useState(''), [statusNotes, setStatusNotes] = useState('');
  useEffect(() => { let current = true; setDetail(null); setError(null); setLoading(true); api.detail(id).then(value => { if (current) setDetail(value); }).catch(value => { if (current) setError(value); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [api, id, revision]);
  useEffect(() => { let current = true; setAttachments([]); setFeedback(null); setEngagementError(null); setEngagementLoading(true); Promise.all([api.attachments(id), api.feedback(id)]).then(([attachmentRows, feedbackRow]) => { if (current) { setAttachments(attachmentRows); setFeedback(feedbackRow); } }).catch(value => { if (current) setEngagementError(value); }).finally(() => { if (current) setEngagementLoading(false); }); return () => { current = false; }; }, [api, id, revision]);
  useEffect(() => { if (!visits) return; let current = true; setVisitError(null); visits.list({ serviceRequestId: id, page: 0, size: 100 }).then(value => { if (current) setVisitData(value.items); }).catch(value => { if (current) setVisitError(value); }); return () => { current = false; }; }, [visits, id, revision]);
  const mutate = async action => { setBusy(true); setError(null); try { const returned = await action(); setDetail(returned); setTechnician(null); setNotes(''); setStatusNotes(''); setToStatus(''); } catch (value) { setDetail(null); setError(value); } finally { setBusy(false); } };
  const openAttachment = async attachment => {
    setEngagementBusy(true); setEngagementError(null);
    try {
      const response = await api.downloadAttachment(id, attachment.id);
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      window.open(url, '_blank', 'noopener,noreferrer');
      window.setTimeout(() => URL.revokeObjectURL(url), 60000);
    } catch (value) { setEngagementError(value); } finally { setEngagementBusy(false); }
  };
  const deleteAttachment = async attachment => {
    if (!window.confirm('Delete attachment "' + attachment.originalFilename + '"?')) return;
    setEngagementBusy(true); setEngagementError(null);
    try { await api.deleteAttachment(id, attachment.id); setRevision(value => value + 1); }
    catch (value) { setEngagementError(value); }
    finally { setEngagementBusy(false); }
  };
  const terminal = detail && ['COMPLETED', 'CANCELLED'].includes(detail.request.status);
  return <section className="asset-form panel"><div className="page-actions"><button className="secondary-btn" disabled={busy || engagementBusy} onClick={onBack}>Back to requests</button><button className="secondary-btn" disabled={busy || engagementBusy || loading} onClick={() => setRevision(value => value + 1)}>Reload detail</button></div><ErrorState error={error} />{loading ? <p role="status">Loading request...</p> : detail && <><RequestDetail detail={detail} attachments={attachments} feedback={feedback} engagementError={engagementError} engagementLoading={engagementLoading} engagementBusy={engagementBusy} onOpenAttachment={openAttachment} onDeleteAttachment={deleteAttachment} />{visits && <><ErrorState error={visitError} /><VisitSummary visits={visitData} />{!terminal && <VisitScheduler detail={detail} visits={visitData} visitApi={visits} busy={busy} onSaved={() => setRevision(value => value + 1)} />}</>}{!terminal && <><h3>Assign / reassign technician</h3><p>Reassignment releases the current assignment. An advanced reassignment must be accepted in the technician client before further progress.</p><DirectoryPicker api={api} kind="technicians" selected={technician} onSelect={setTechnician} disabled={busy} /><label>Assignment notes<textarea maxLength={2000} disabled={busy} value={notes} onChange={event => setNotes(event.target.value)} /></label><button className="primary-btn" disabled={busy || !technician} onClick={() => { if (window.confirm('Assign selected technician and release any current assignment?')) mutate(() => api.assign(detail, technician, notes)); }}>Assign technician</button>
    <h3>Update status</h3><p>Actions depend on the latest backend state. Completion requires the active assignment's valid technician report. Reports and the technician acceptance endpoint are not available here.</p><form onSubmit={event => { event.preventDefault(); if (window.confirm('Submit status ' + toStatus + '?')) mutate(() => api.status(detail, toStatus, statusNotes)); }}><label>Next status<select required disabled={busy} value={toStatus} onChange={event => setToStatus(event.target.value)}><option value="">Select action</option>{nextStatuses(detail).map(value => <option key={value}>{value}</option>)}</select></label><label>Notes / cancellation reason<textarea disabled={busy} maxLength={2000} required={['CANCELLED', 'WAITING_FOR_PARTS'].includes(toStatus)} value={statusNotes} onChange={event => setStatusNotes(event.target.value)} /></label><button className="primary-btn" disabled={busy || !toStatus}>Submit status</button></form></>}</>}</section>;
}

export function WorkflowPage({ api, assets, visits, user }) {
  const [page, setPage] = useState(0), [status, setStatus] = useState(''), [priority, setPriority] = useState(''), [data, setData] = useState(null), [error, setError] = useState(null), [loading, setLoading] = useState(true), [revision, setRevision] = useState(0), [view, setView] = useState(null);
  const allowed = isAdmin(user);
  const [q, setQ] = useState('');
  const matches = (row, term) => JSON.stringify(row).toLowerCase().includes(term.trim().toLowerCase());
  useEffect(() => { if (!allowed || view) return; let current = true; setData(null); setError(null); setLoading(true); const searching = Boolean(q.trim()); api.list({ page: searching ? 0 : page, size: searching ? 100 : 10, status, priority }).then(value => { if (!current) return; if (searching) { const items = value.items.filter(row => matches(row, q)); const start = page * 10; setData({ ...value, page, size: 10, totalElements: items.length, totalPages: Math.ceil(items.length / 10), items: items.slice(start, start + 10) }); } else setData(value); }).catch(value => { if (current) setError(value); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [api, allowed, view, page, status, priority, q, revision]);
  if (!allowed) return <p role="alert">Access denied. Administrator role required.</p>;
  if (view === 'create') return <CreateRequest api={api} assets={assets} onClose={() => setView(null)} onSaved={value => setView(value.request.id)} />;
  if (view) return <DetailPage key={view} id={view} api={api} visits={visits} onBack={() => setView(null)} />;
  return <><div className="page-header"><div><div className="eyebrow">SERVICE OPERATIONS</div><h1>Service requests</h1></div><button className="primary-btn" onClick={() => setView('create')}>Create request</button></div><section className="asset-form panel"><div className="table-controls four-controls"><label>Status<select value={status} onChange={event => { setData(null); setStatus(event.target.value); setPage(0); }}><option value="">All</option>{statuses.map(value => <option key={value}>{value}</option>)}</select></label><label>Priority<select value={priority} onChange={event => { setData(null); setPriority(event.target.value); setPage(0); }}><option value="">All</option>{priorities.map(value => <option key={value}>{value}</option>)}</select></label><label>Search<input value={q} onChange={event => { setQ(event.target.value); setPage(0); }} placeholder="Search requests"/></label><button className="secondary-btn" disabled={loading} onClick={() => setRevision(value => value + 1)}>Refresh Requests</button></div><ErrorState error={error} />{loading ? <p role="status">Loading requests...</p> : <DataTable empty="No service requests found." rows={data?.items || []} columns={[{key:'serviceId',label:'Request'},{key:'title',label:'Title'},{key:'status',label:'Status',render:r=><StatusChip value={r.status}/>},{key:'priority',label:'Priority',render:r=><PriorityChip value={r.priority}/>}]} onRow={request => setView(request.id)} />}<Pager data={data} page={page} onPage={value => { setData(null); setPage(value); }} busy={loading} /></section></>;
}
