import React, { useEffect, useState } from 'react';
import { priorities, serviceTypes, statuses, relatedAssets, nextStatuses } from './api/workflow.js';
import { isAdmin } from './api/services.js';
import { ErrorState, displayValue } from './assetModules.jsx';
import './workflow.css';

export function Pager({ data, page, onPage, busy }) {
  return <div className="page-actions"><button type="button" className="secondary-btn" disabled={busy || page === 0} onClick={() => onPage(page - 1)}>Previous</button><span>Page {page + 1}{data ? ` - ${data.totalElements} results` : ''}</span><button type="button" className="secondary-btn" disabled={busy || !data || page + 1 >= data.totalPages} onClick={() => onPage(page + 1)}>Next</button></div>;
}

export function DirectoryPicker({ api, kind, selected, onSelect, disabled = false }) {
  const [q, setQ] = useState(''), [page, setPage] = useState(0), [data, setData] = useState(null), [error, setError] = useState(null), [loading, setLoading] = useState(true), [revision, setRevision] = useState(0);
  useEffect(() => { let current = true; setData(null); setLoading(true); setError(null); api.directory(kind, { q, page, size: 10, active: true }).then(value => { if (current) setData(value); }).catch(value => { if (current) setError(value); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [api, kind, q, page, revision]);
  const changePage = value => { setData(null); setPage(value); };
  return <fieldset disabled={disabled} className="workflow-picker"><legend>{kind === 'customers' ? 'Customer' : 'Technician'} selection</legend>
    <label>Search {kind}<input maxLength={254} value={q} onChange={event => { setData(null); setQ(event.target.value); setPage(0); }} placeholder="Search by name, email or supported directory fields" /></label>
    {selected && <p role="status">Selected: {selected.fullName || selected.employeeId || selected.email} <button type="button" className="secondary-btn" onClick={() => onSelect(null)}>Clear selection</button></p>}
    <ErrorState error={error} />{error && <button type="button" className="secondary-btn" onClick={() => setRevision(value => value + 1)}>Retry directory</button>}
    {loading ? <p role="status">Loading directory...</p> : data?.items.length === 0 ? <p>No matching {kind}.</p> : <ul>{data?.items.map(row => <li key={row.customerProfileId ?? row.technicianProfileId}><button type="button" className="secondary-btn" disabled={!row.active || (kind === 'customers' && row.status !== 'ACTIVE')} onClick={() => onSelect(row)}>{row.fullName || row.employeeId || row.email} - {row.email || 'Phone-only account'}{kind === 'technicians' ? ` - ${row.assignedArea || 'Area not provided'} - ${row.availabilityStatus}` : ` - ${row.status}`}</button></li>)}</ul>}
    <Pager data={data} page={page} onPage={changePage} busy={loading || disabled} /></fieldset>;
}

export function CreateRequest({ api, assets, onSaved, onClose }) {
  const [customer, setCustomer] = useState(null), [draft, setDraft] = useState({ priority: 'MEDIUM', serviceType: '' }), [buildings, setBuildings] = useState([]), [lifts, setLifts] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(null), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0);
  useEffect(() => { let current = true; setLoading(true); setBuildings([]); setLifts([]); setError(null); Promise.all([assets.buildings.list(), assets.lifts.list()]).then(([b, l]) => { if (current) { setBuildings(b); setLifts(l); } }).catch(value => { if (current) setError(value); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [assets, revision]);
  const related = relatedAssets(customer, buildings, lifts, draft.buildingId);
  const submit = async event => { event.preventDefault(); setBusy(true); setError(null); try { onSaved(await api.create(draft, customer, buildings, lifts)); } catch (value) { setError(value); } finally { setBusy(false); } };
  return <form className="asset-form panel" onSubmit={submit}><h2>Create service request</h2><p>Select an active customer, then their building and lift. The backend revalidates ownership and eligibility.</p>
    <DirectoryPicker api={api} kind="customers" selected={customer} disabled={busy} onSelect={value => { setCustomer(value); setDraft(current => ({ ...current, buildingId: '', liftId: '' })); }} />
    {loading && <p role="status">Loading assets...</p>}<ErrorState error={error} />{error && <button type="button" className="secondary-btn" disabled={busy} onClick={() => setRevision(value => value + 1)}>Reload assets</button>}
    <fieldset disabled={busy || loading}><div className="asset-fields"><label>Building *<select required value={draft.buildingId || ''} onChange={event => setDraft(current => ({ ...current, buildingId: event.target.value, liftId: '' }))}><option value="">Select customer building</option>{related.buildings.map(building => <option key={building.id} value={building.id}>{building.buildingName}</option>)}</select></label>
      <label>Lift *<select required value={draft.liftId || ''} onChange={event => setDraft(current => ({ ...current, liftId: event.target.value }))}><option value="">Select building lift</option>{related.lifts.map(lift => <option key={lift.id} value={lift.id}>{lift.name} - {lift.currentStatus}</option>)}</select></label>
      <label>Service type *<select required value={draft.serviceType} onChange={event => setDraft(current => ({ ...current, serviceType: event.target.value }))}><option value="">Select type</option>{serviceTypes.map(value => <option key={value}>{value}</option>)}</select></label>
      <label>Priority *<select value={draft.priority} onChange={event => setDraft(current => ({ ...current, priority: event.target.value }))}>{priorities.map(value => <option key={value}>{value}</option>)}</select></label>
      {[['title', 'Title', 200, true], ['description', 'Description', null, true], ['issueCategory', 'Issue category', 100], ['customerRemarks', 'Customer remarks', 2000], ['internalAdminNotes', 'Internal admin notes', 2000], ['preferredVisitDate', 'Preferred visit date', null, false, 'date'], ['preferredTimeSlot', 'Preferred time slot', 80], ['estimatedCompletionMinutes', 'Estimated completion minutes', null, false, 'number']].map(([key, label, max, required, type]) => <label key={key}>{label}{required ? ' *' : ''}{['description', 'customerRemarks', 'internalAdminNotes'].includes(key) ? <textarea required={required} maxLength={max ?? undefined} value={draft[key] ?? ''} onChange={event => setDraft(current => ({ ...current, [key]: event.target.value }))} /> : <input required={required} maxLength={max ?? undefined} type={type || 'text'} min={type === 'number' ? 0 : undefined} max={type === 'number' ? 2147483647 : undefined} step={type === 'number' ? 1 : undefined} value={draft[key] ?? ''} onChange={event => setDraft(current => ({ ...current, [key]: event.target.value }))} />}</label>)}</div></fieldset>
    {!loading && customer && !related.buildings.length && <p>No active buildings for this customer.</p>}{draft.buildingId && !related.lifts.length && <p>No active lifts for this building.</p>}
    <div className="page-actions"><button type="button" className="secondary-btn" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy || loading || !customer || !related.lifts.length}>{busy ? 'Creating...' : 'Create request'}</button></div></form>;
}

const fields = (record, keys) => <dl>{keys.map(key => <React.Fragment key={key}><dt>{key}</dt><dd>{displayValue(record[key])}</dd></React.Fragment>)}</dl>;

function RequestEngagement({ attachments = [], feedback = null, error = null, loading = false, busy = false, onOpenAttachment, onDeleteAttachment }) {
  return <><h3>Customer attachments</h3><ErrorState error={error} />{loading ? <p role="status">Loading attachments and feedback...</p> : attachments.length ? <div className="asset-table"><table><thead><tr><th>File</th><th>Type</th><th>Size</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{attachments.map(attachment => <tr key={attachment.id}><td>{attachment.originalFilename}</td><td>{attachment.contentType}</td><td>{displayValue(attachment.fileSize)}</td><td>{displayValue(attachment.createdAt)}</td><td><button type="button" className="secondary-btn" disabled={busy} onClick={() => onOpenAttachment(attachment)}>Open</button><button type="button" className="secondary-btn" disabled={busy} onClick={() => onDeleteAttachment(attachment)}>Delete</button></td></tr>)}</tbody></table></div> : <p>No customer attachments returned.</p>}
    <h3>Customer feedback</h3>{feedback ? fields(feedback, ['rating', 'comment', 'createdAt', 'updatedAt']) : <p>No customer feedback returned.</p>}</>;
}

export function RequestDetail({ detail, attachments = [], feedback = null, engagementError = null, engagementLoading = false, engagementBusy = false, onOpenAttachment, onDeleteAttachment }) {
  return <><h2>{detail.request.serviceId} - {detail.request.title}</h2>{fields(detail.request, ['id', 'customerProfileId', 'liftId', 'status', 'priority', 'serviceType', 'description', 'issueCategory', 'customerRemarks', 'technicianRemarks', 'internalAdminNotes', 'preferredVisitDate', 'preferredTimeSlot', 'estimatedCompletionMinutes', 'serviceRequestedAt', 'completedAt'])}
    <h3>Active assignment</h3>{detail.activeAssignment ? fields(detail.activeAssignment, ['id', 'technicianProfileId', 'status', 'assignedAt', 'acceptedAt', 'notes']) : <p>No active assignment.</p>}
    <h3>Status history</h3>{detail.history.length ? <ol>{detail.history.map(history => <li key={history.id}>{history.fromStatus ?? 'Created'} to {history.toStatus} - {displayValue(history.changedAt)}<p>{displayValue(history.notes)}</p></li>)}</ol> : <p>No status history returned.</p>}
    <h3>Service report (read only)</h3>{detail.report ? fields(detail.report, ['id', 'assignmentId', 'diagnosis', 'workPerformed', 'testingResult', 'completionNotes', 'createdAt', 'updatedAt']) : <p>No service report returned.</p>}
    <RequestEngagement attachments={attachments} feedback={feedback} error={engagementError} loading={engagementLoading} busy={engagementBusy} onOpenAttachment={onOpenAttachment} onDeleteAttachment={onDeleteAttachment} /></>;
}

function VisitSummary({ visits }) {
  const active = visits.filter(visit => ['SCHEDULED', 'IN_PROGRESS'].includes(visit.status));
  return <><h3>Service visits</h3>{visits.length === 0 ? <p>No visit scheduled yet.</p> : <><h4>Current / upcoming</h4>{active.length ? <ol>{active.map(visit => <li key={visit.id}>{visit.status} - {visit.scheduledDate} {String(visit.startTime).slice(0, 5)}-{String(visit.endTime).slice(0, 5)} - Technician #{visit.technicianProfileId}</li>)}</ol> : <p>No active or upcoming visit.</p>}<h4>Visit history</h4><ol>{visits.map(visit => <li key={visit.id}>{visit.serviceId} - {visit.status} - {visit.scheduledDate} {String(visit.startTime).slice(0, 5)}-{String(visit.endTime).slice(0, 5)}<p>{displayValue(visit.notes)}</p></li>)}</ol></>}</>;
}

function VisitScheduler({ detail, visits, visitApi, onSaved, busy }) {
  const assignment = detail.activeAssignment, active = visits.some(visit => ['SCHEDULED', 'IN_PROGRESS'].includes(visit.status));
  const [draft, setDraft] = useState({ scheduledDate: '', startTime: '', endTime: '', notes: '' }), [error, setError] = useState(null), [saving, setSaving] = useState(false);
  if (!assignment) return <p>Assign a technician before scheduling a visit.</p>;
  if (active) return <p>An active or upcoming visit already exists for this request.</p>;
  const submit = async event => { event.preventDefault(); setSaving(true); setError(null); try { await visitApi.create({ ...draft, serviceRequestId: detail.request.id, technicianProfileId: assignment.technicianProfileId }); setDraft({ scheduledDate: '', startTime: '', endTime: '', notes: '' }); onSaved(); } catch (value) { setError(value); } finally { setSaving(false); } };
  return <form className="workflow-picker" onSubmit={submit}><legend>Schedule replacement / next visit</legend><ErrorState error={error} /><fieldset disabled={busy || saving}><div className="asset-fields"><label>Date<input required type="date" value={draft.scheduledDate} onChange={event => setDraft(current => ({ ...current, scheduledDate: event.target.value }))} /></label><label>Start<input required type="time" value={draft.startTime} onChange={event => setDraft(current => ({ ...current, startTime: event.target.value }))} /></label><label>End<input required type="time" value={draft.endTime} onChange={event => setDraft(current => ({ ...current, endTime: event.target.value }))} /></label></div><label>Notes<textarea maxLength={2000} value={draft.notes} onChange={event => setDraft(current => ({ ...current, notes: event.target.value }))} /></label><button className="primary-btn" disabled={saving}>{saving ? 'Scheduling...' : 'Schedule visit'}</button></fieldset></form>;
}

export function DetailPage({ id, api, visits, onBack }) {
  const [detail, setDetail] = useState(null), [visitData, setVisitData] = useState([]), [attachments, setAttachments] = useState([]), [feedback, setFeedback] = useState(null), [error, setError] = useState(null), [visitError, setVisitError] = useState(null), [engagementError, setEngagementError] = useState(null), [loading, setLoading] = useState(true), [engagementLoading, setEngagementLoading] = useState(false), [engagementBusy, setEngagementBusy] = useState(false), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0), [technician, setTechnician] = useState(null), [notes, setNotes] = useState(''), [toStatus, setToStatus] = useState(''), [statusNotes, setStatusNotes] = useState('');
  useEffect(() => { let current = true; setDetail(null); setError(null); setLoading(true); api.detail(id).then(value => { if (current) setDetail(value); }).catch(value => { if (current) setError(value); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [api, id, revision]);
  useEffect(() => { let current = true; setAttachments([]); setFeedback(null); setEngagementError(null); setEngagementLoading(true); Promise.all([api.attachments(id), api.feedback(id)]).then(([attachmentRows, feedbackRow]) => { if (current) { setAttachments(attachmentRows); setFeedback(feedbackRow); } }).catch(value => { if (current) setEngagementError(value); }).finally(() => { if (current) setEngagementLoading(false); }); return () => { current = false; }; }, [api, id, revision]);
  useEffect(() => { if (!visits) return; let current = true; setVisitError(null); visits.list({ serviceRequestId: id, page: 0, size: 100 }).then(value => { if (current) setVisitData(value.items); }).catch(value => { if (current) setVisitError(value); }); return () => { current = false; }; }, [visits, id, revision]);
  const mutate = async action => { setBusy(true); setError(null); try { const returned = await action(); setDetail(returned); setTechnician(null); setNotes(''); setStatusNotes(''); setToStatus(''); } catch (value) { setDetail(null); setError(value); } finally { setBusy(false); } };
  const openAttachment = async attachment => {
    setEngagementBusy(true); setEngagementError(null);
    try {
      const response = await api.downloadAttachment(id, attachment.id);
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      window.open(url, '_blank', 'noopener,noreferrer');
      window.setTimeout(() => URL.revokeObjectURL(url), 60000);
    } catch (value) { setEngagementError(value); } finally { setEngagementBusy(false); }
  };
  const deleteAttachment = async attachment => {
    if (!window.confirm('Delete attachment "' + attachment.originalFilename + '"?')) return;
    setEngagementBusy(true); setEngagementError(null);
    try { await api.deleteAttachment(id, attachment.id); setRevision(value => value + 1); }
    catch (value) { setEngagementError(value); }
    finally { setEngagementBusy(false); }
  };
  const terminal = detail && ['COMPLETED', 'CANCELLED'].includes(detail.request.status);
  return <section className="asset-form panel"><div className="page-actions"><button className="secondary-btn" disabled={busy || engagementBusy} onClick={onBack}>Back to requests</button><button className="secondary-btn" disabled={busy || engagementBusy || loading} onClick={() => setRevision(value => value + 1)}>Reload detail</button></div><ErrorState error={error} />{loading ? <p role="status">Loading request...</p> : detail && <><RequestDetail detail={detail} attachments={attachments} feedback={feedback} engagementError={engagementError} engagementLoading={engagementLoading} engagementBusy={engagementBusy} onOpenAttachment={openAttachment} onDeleteAttachment={deleteAttachment} />{visits && <><ErrorState error={visitError} /><VisitSummary visits={visitData} />{!terminal && <VisitScheduler detail={detail} visits={visitData} visitApi={visits} busy={busy} onSaved={() => setRevision(value => value + 1)} />}</>}{!terminal && <><h3>Assign / reassign technician</h3><p>Reassignment releases the current assignment. An advanced reassignment must be accepted in the technician client before further progress.</p><DirectoryPicker api={api} kind="technicians" selected={technician} onSelect={setTechnician} disabled={busy} /><label>Assignment notes<textarea maxLength={2000} disabled={busy} value={notes} onChange={event => setNotes(event.target.value)} /></label><button className="primary-btn" disabled={busy || !technician} onClick={() => { if (window.confirm('Assign selected technician and release any current assignment?')) mutate(() => api.assign(detail, technician, notes)); }}>Assign technician</button>
    <h3>Update status</h3><p>Actions depend on the latest backend state. Completion requires the active assignment's valid technician report. Reports and the technician acceptance endpoint are not available here.</p><form onSubmit={event => { event.preventDefault(); if (window.confirm('Submit status ' + toStatus + '?')) mutate(() => api.status(detail, toStatus, statusNotes)); }}><label>Next status<select required disabled={busy} value={toStatus} onChange={event => setToStatus(event.target.value)}><option value="">Select action</option>{nextStatuses(detail).map(value => <option key={value}>{value}</option>)}</select></label><label>Notes / cancellation reason<textarea disabled={busy} maxLength={2000} required={['CANCELLED', 'WAITING_FOR_PARTS'].includes(toStatus)} value={statusNotes} onChange={event => setStatusNotes(event.target.value)} /></label><button className="primary-btn" disabled={busy || !toStatus}>Submit status</button></form></>}</>}</section>;
}

export function WorkflowPage({ api, assets, visits, user }) {
  const [page, setPage] = useState(0), [status, setStatus] = useState(''), [priority, setPriority] = useState(''), [data, setData] = useState(null), [error, setError] = useState(null), [loading, setLoading] = useState(true), [revision, setRevision] = useState(0), [view, setView] = useState(null);
  const allowed = isAdmin(user);
  useEffect(() => { if (!allowed || view) return; let current = true; setData(null); setError(null); setLoading(true); api.list({ page, size: 20, status, priority }).then(value => { if (current) setData(value); }).catch(value => { if (current) setError(value); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [api, allowed, view, page, status, priority, revision]);
  if (!allowed) return <p role="alert">Access denied. Administrator role required.</p>;
  if (view === 'create') return <CreateRequest api={api} assets={assets} onClose={() => setView(null)} onSaved={value => setView(value.request.id)} />;
  if (view) return <DetailPage key={view} id={view} api={api} visits={visits} onBack={() => setView(null)} />;
  return <><div className="page-header"><div><div className="eyebrow">SERVICE OPERATIONS</div><h1>Service requests</h1></div><button className="primary-btn" onClick={() => setView('create')}>Create request</button></div><section className="asset-form panel"><div className="asset-fields">{[['Status', statuses, status, setStatus], ['Priority', priorities, priority, setPriority]].map(([label, options, value, setter]) => <label key={label}>{label}<select value={value} onChange={event => { setData(null); setter(event.target.value); setPage(0); }}><option value="">All</option>{options.map(value => <option key={value}>{value}</option>)}</select></label>)}</div><button className="secondary-btn" disabled={loading} onClick={() => setRevision(value => value + 1)}>Refresh requests</button><ErrorState error={error} />{loading ? <p role="status">Loading requests...</p> : data?.items.length === 0 ? <p>No service requests found.</p> : <div className="asset-table"><table><thead><tr><th>Request</th><th>Title</th><th>Status</th><th>Priority</th><th>Action</th></tr></thead><tbody>{data?.items.map(request => <tr key={request.id}><td>{request.serviceId}</td><td>{request.title}</td><td>{request.status}</td><td>{request.priority}</td><td><button className="secondary-btn" onClick={() => setView(request.id)}>View detail</button></td></tr>)}</tbody></table></div>}<Pager data={data} page={page} onPage={value => { setData(null); setPage(value); }} busy={loading} /></section></>;
}
